// bonus/svelteapp/src/components/Header.svelte
<script lang="ts">
	import { order } from '../store/stores';

	$: count = $order.productCount || 0;
	$: displayText =
		count === 0 ? '(No Selection)' : `${count} product(s), ` + `$${$order.total.toFixed(2)}`;
</script>

<div class="p-1 bg-secondary text-white text-end">
	{displayText}
	<a href="/order" class="btn btn-sm btn-primary m-1"> Submit Order </a>
</div>

// ch.16/webapp5/src/header.tsx
import { createElement } from "./tools/jsxFactory";
import { Order } from "./data/entities";

export class Header {
    props: {
        order: Order,
        submitCallback: () => void
    }

    getContent(): HTMLElement {
        let count = this.props.order.productCount;

        return <div className="p-1 bg-secondary text-white text-end">
            {count === 0 ? "(No Selection)"
                : `${count} product(s), $${this.props.order.total.toFixed(2)}`}
            <button className="btn btn-primary m-1"
                onclick={this.props.submitCallback}>
                Submit Order
            </button>
        </div>
    }
}
