// bonus/svelteapp/src/components/ProductItem.svelte
<script lang="ts">
	import type { Product } from '../data/entities';
	import { createEventDispatcher } from 'svelte';

	const dispatch = createEventDispatcher<{ addToCart: { product: Product; quantity: number } }>();

	export let product: Product;
	let quantity: string;

	function handleAddToCart() {
		dispatch('addToCart', {
			product: product,
			quantity: Number(quantity)
		});
	}
</script>

<div class="card m-1 p-1 bg-light">
	<h4>
		{product.name}
		<span class="badge rounded-pill bg-primary float-end">
			${product.price.toFixed(2)}
		</span>
	</h4>
	<div class="card-text bg-white p-1">
		{product.description}
		<button class="btn btn-success btn-sm float-end" on:click={handleAddToCart}>
			Add To Cart
		</button>
		<select class="form-control-inline float-end m-1" bind:value={quantity}>
			<option>1</option>
			<option>2</option>
			<option>3</option>
		</select>
	</div>
</div>

// ch.16/webapp5/src/productItem.tsx
import { createElement } from "./tools/jsxFactory";
import { Product } from "./data/entities";

export class ProductItem {
    private quantity: number = 1;

    props: {
        product: Product,
        callback: (product: Product, quantity: number) => void
    }

    getContent(): HTMLElement {
        return <div className="card m-1 p-1 bg-light">
            <h4>
                {this.props.product.name}
                <span className="badge rounded-pill bg-primary float-end">
                    ${this.props.product.price.toFixed(2)}
                </span>
            </h4>
            <div className="card-text bg-white p-1">
                {this.props.product.description}
                <button className="btn btn-success btn-sm float-end"
                    onclick={this.handleAddToCart} >
                    Add To Cart
                </button>
                <select className="form-control-inline float-end m-1"
                    onchange={this.handleQuantityChange}>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                </select>
            </div>
        </div>
    }

    handleQuantityChange = (ev: Event): void => {
        this.quantity = Number((ev.target as HTMLSelectElement).value);
    }

    handleAddToCart = (): void => {
        this.props.callback(this.props.product, this.quantity);
    }
}
