// ch.16/webapp5/src/categoryList.tsx
import { createElement } from "./tools/jsxFactory";

export class CategoryList {
    props: {
        categories: string[];
        selectedCategory: string,
        callback: (selected: string) => void
    }

    getContent(): HTMLElement {
        return <div className="d-grid gap-2">
            {["All", ...this.props.categories].map(c => 
                this.getCategoryButton(c))}
        </div>
    }

    getCategoryButton(cat?: string): HTMLElement {
        let selected = this.props.selectedCategory === undefined
            ? "All" : this.props.selectedCategory;
        let btnClass = selected === cat ? 
            "btn-primary" : "btn-secondary";

        return <button className={`btn ${btnClass}`}
            onclick={() => this.props.callback(cat)}>
            {cat}
        </button>
    }
}

// bonus/svelteapp/src/components/CategoryList.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';

	const dispatch = createEventDispatcher
		<{ selectCategory: string }>();

	export let categories: string[] = [];
	let selected: string = 'All';

	function selectCategory(category: string) {
		selected = category;
		dispatch('selectCategory', selected);
	}

	function getButtonClasses(category: string): string {
		const btnClass = selected === category ? 'btn-primary' : 'btn-secondary';
		return `btn ${btnClass}`;
	}
</script>

<div class="d-grid gap-2">
	{#each categories as c}
		<button class={getButtonClasses(c)} on:click={() => selectCategory(c)}>
			{c}
		</button>
	{/each}
</div>
